<a href="https://colab.research.google.com/github/asnaraliya/ICT/blob/main/numpypandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.arange(10, 50)
matrix = arr.reshape(4, 10)
last_col = matrix[:, -1]

print(matrix)
print("Last column:", last_col)


[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Last column: [19 29 39 49]


In [2]:
A = np.full((3, 3), 5)
B = np.arange(1, 10).reshape(3, 3)

add = A + B
multiply = A * B
transpose = multiply.T

print("Addition:\n", add)
print("Multiplication:\n", multiply)
print("Transpose:\n", transpose)


Addition:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Multiplication:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Transpose:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [3]:
rand_arr = np.random.randint(10, 100, 15)
replaced = np.where(rand_arr > 50, -1, rand_arr)
count = np.sum(rand_arr > 50)

print("Original:", rand_arr)
print("Replaced:", replaced)
print("Count replaced:", count)


Original: [40 14 63 84 76 63 96 53 45 20 10 29 35 34 97]
Replaced: [40 14 -1 -1 -1 -1 -1 -1 45 20 10 29 35 34 -1]
Count replaced: 7


In [4]:
arr = np.random.rand(5, 4)
row_sums = arr.sum(axis=1)
max_row_index = np.argmax(row_sums)

normalized = (arr - arr.min(axis=1)[:, None]) / (arr.max(axis=1) - arr.min(axis=1))[:, None]

print("Array:\n", arr)
print("Row with max sum:", max_row_index)
print("Normalized:\n", normalized)


Array:
 [[0.02018069 0.12927489 0.33670325 0.88960973]
 [0.55450934 0.18966648 0.4632558  0.41916763]
 [0.72402074 0.20167487 0.70898416 0.56397417]
 [0.40308841 0.03068471 0.51216754 0.42466282]
 [0.10225353 0.80104587 0.11629423 0.5131292 ]]
Row with max sum: 2
Normalized:
 [[0.         0.12547799 0.36405796 1.        ]
 [1.         0.         0.74988261 0.62904108]
 [1.         0.         0.97121335 0.69360038]
 [0.77345167 0.         1.         0.81825995]
 [0.         1.         0.02009281 0.58797964]]


In [5]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique = np.unique(arr)
duplicates = [x for x in unique if np.count_nonzero(arr == x) > 1]

print("Unique:", unique)
print("Duplicates:", duplicates)


Unique: [1 3 5 7 9]
Duplicates: [np.int64(1), np.int64(3), np.int64(5)]


In [6]:
arr = np.arange(1, 37).reshape(6, 6)
submatrix = arr[1:5, 1:5]
evens = submatrix[submatrix % 2 == 0]

print("Submatrix:\n", submatrix)
print("Even numbers:", evens)


Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even numbers: [ 8 10 14 16 20 22 26 28]


In [7]:
arr = np.arange(12).reshape(3, 4)
reshaped = arr.reshape(2, 6)
flattened = reshaped.flatten()
back = flattened.reshape(4, 3)

print("Reshaped:\n", reshaped)
print("Flattened:", flattened)
print("Back to (4,3):\n", back)


Reshaped:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Back to (4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
a = np.array([[1, 2], [3, 4]])
a = np.vstack([a, [5, 6]])
a = np.column_stack([a, [7, 8, 9]])

print(a)


[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined = np.concatenate([a, b, c]).reshape(3, 3)
diag = np.diag(joined)

print("Matrix:\n", joined)
print("Diagonal:", diag)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal: [1 5 9]


In [10]:
arr = np.arange(1, 21)
divisible = arr[(arr % 3 == 0) | (arr % 5 == 0)]
count = divisible.size

print("Divisible:", divisible)
print("Count:", count)


Divisible: [ 3  5  6  9 10 12 15 18 20]
Count: 9


In [14]:
import pandas as pd
df = pd.read_csv("titanic_dataset.csv")
df.head(10)


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C


In [15]:
df.isnull().sum()


,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


In [16]:
df.groupby("Sex")["Survived"].mean() * 100


,Survived
Sex,
female,74.203822
male,18.890815


In [17]:
df["Age"].mean(), df["Age"].median(), df["Age"].std()


(np.float64(29.69911764705882), 28.0, 14.526497332334044)

In [18]:
df["Pclass"].value_counts()


,count
Pclass,
3,491
1,216
2,184


In [19]:
df[(df["Sex"]=="female") & (df["Age"]<18) & (df["Survived"]==1)]


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.00,0,0,35851,7.7333,NaN,Q
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S


In [20]:
median_age = df["Age"].median()
df["Age"].fillna(median_age, inplace=True)


/tmp/ipykernel_3487/3827535355.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(median_age, inplace=True)


In [21]:
df["age_group"] = pd.cut(df["Age"], bins=[0,18,60,120], labels=["Child","Adult","Senior"])
df[["Age","age_group"]].head(10)


,Age,age_group
0,22.0,Adult
1,38.0,Adult
2,26.0,Adult
3,35.0,Adult
4,35.0,Adult
5,28.0,Adult
6,54.0,Adult
7,2.0,Child
8,27.0,Adult
9,14.0,Child


In [22]:
df.nlargest(5, "Fare")[["Name","Fare","Pclass","Sex"]]


,Name,Fare,Pclass,Sex
258,"Ward, Miss. Anna",512.3292,1,female
679,"Cardeza, Mr. Thomas Drake Martinez",512.3292,1,male
737,"Lesurer, Mr. Gustave J",512.3292,1,male
27,"Fortune, Mr. Charles Alexander",263.0000,1,male
88,"Fortune, Miss. Mabel Helen",263.0000,1,female


In [23]:
df.groupby(["Pclass","Sex"])["Fare"].mean()


Pclass  Sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [24]:
df.rename(columns={"Sex":"gender","Fare":"ticket_fare"}, inplace=True)
df.head(5)



,PassengerId,Survived,Pclass,Name,gender,Age,SibSp,Parch,Ticket,ticket_fare,Cabin,Embarked,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult


In [25]:
df.groupby("Pclass")["Survived"].value_counts()


Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

In [26]:
df.groupby(["Pclass","gender"])["Age"].mean()


Pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: Age, dtype: float64